package forgejo

import (
	"archive/tar"
	"bytes"
	"context"
	"strings"
	"testing"
)

func syntheticGitTar(t *testing.T, extra ...tarEntry) []byte {
	t.Helper()
	entries := syntheticGitEntries()
	entries = append(entries, extra...)
	return makeTar(t, entries...)
}

func syntheticGitEntries() []tarEntry {
	return []tarEntry{
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git", Typeflag: tar.TypeDir}},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/HEAD"}, body: []byte("ref: refs/heads/main\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/config"}, body: []byte("[core]\n\tbare = true\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/description"}, body: []byte("Unnamed repository\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/refs/heads/main"}, body: []byte(strings.Repeat("a", 40) + "\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/objects/ab/cdef"}, body: []byte("packed-or-loose-object")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/pre-receive"}, body: []byte("#!/bin/sh\n# AUTO GENERATED BY GITEA\nexit 0\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/pre-receive.sample"}, body: []byte("generated sample\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/custom-hook"}, body: []byte("#!/bin/sh\necho user hook\n")},
		{header: tar.Header{Name: ".rehearse-runtime/app.ini"}, body: []byte("generated config\n")},
		{header: tar.Header{Name: "gitea/log/forgejo.log"}, body: []byte("volatile log line\n")},
	}
}

func changedSyntheticGitFile(t *testing.T, name string, body []byte) []byte {
	t.Helper()
	entries := syntheticGitEntries()
	for i := range entries {
		if entries[i].header.Name == name {
			entries[i].body = bytes.Clone(body)
			entries[i].header.Size = int64(len(body))
			return makeTar(t, entries...)
		}
	}
	t.Fatalf("synthetic Git file %q was not found", name)
	return nil
}

func TestProjectRepositoryFilesIsTarOrderIndependentAndHashesGitState(t *testing.T) {
	ctx := context.Background()
	first := syntheticGitTar(t)
	got, err := ProjectRepositoryFiles(ctx, bytes.NewReader(first))
	if err != nil {
		t.Fatalf("ProjectRepositoryFiles: %v", err)
	}
	if got.Repositories != 1 || got.Files != 5 || got.Bytes == 0 || len(got.SHA256) != 64 {
		t.Fatalf("unexpected summary: %+v", got)
	}

	// TAR header order is not part of the semantic identity.
	entries := []tarEntry{
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/objects/ab/cdef"}, body: []byte("packed-or-loose-object")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/custom-hook"}, body: []byte("#!/bin/sh\necho user hook\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/refs/heads/main"}, body: []byte(strings.Repeat("a", 40) + "\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/config"}, body: []byte("[core]\n\tbare = true\n")},
		{header: tar.Header{Name: ".rehearse-runtime/app.ini"}, body: []byte("different generated config\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/description"}, body: []byte("changed generated description\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/pre-receive"}, body: []byte("#!/bin/sh\n# AUTO GENERATED BY GITEA\nchanged generated hook\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/HEAD"}, body: []byte("ref: refs/heads/main\n")},
		{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/pre-receive.sample"}, body: []byte("changed sample\n")},
	}
	reordered, err := ProjectRepositoryFiles(ctx, bytes.NewReader(makeTar(t, entries...)))
	if err != nil {
		t.Fatalf("ProjectRepositoryFiles reordered: %v", err)
	}
	if got.SHA256 != reordered.SHA256 || got.Files != reordered.Files || got.Bytes != reordered.Bytes {
		t.Fatalf("projection depends on TAR ordering or generated files: first=%+v reordered=%+v", got, reordered)
	}

	changedRef := syntheticGitTar(t, tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/refs/heads/feature"}, body: []byte(strings.Repeat("b", 40) + "\n")})
	changed, err := ProjectRepositoryFiles(ctx, bytes.NewReader(changedRef))
	if err != nil || changed.SHA256 == got.SHA256 {
		t.Fatalf("changed Git ref was not detected: summary=%+v err=%v", changed, err)
	}
	changedObject := changedSyntheticGitFile(t, "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/objects/ab/cdef", []byte("changed-object-content"))
	changed, err = ProjectRepositoryFiles(ctx, bytes.NewReader(changedObject))
	if err != nil || changed.SHA256 == got.SHA256 {
		t.Fatalf("changed Git object bytes were not detected: summary=%+v err=%v", changed, err)
	}
	changedCustomHook := changedSyntheticGitFile(t, "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/custom-hook", []byte("#!/bin/sh\necho changed custom hook\n"))
	changed, err = ProjectRepositoryFiles(ctx, bytes.NewReader(changedCustomHook))
	if err != nil || changed.SHA256 == got.SHA256 {
		t.Fatalf("custom hook change was hidden by generated-hook exclusion: summary=%+v err=%v", changed, err)
	}
	generatedAcrossChunks := changedSyntheticGitFile(t, "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/hooks/pre-receive", append(bytes.Repeat([]byte{'x'}, 32760), []byte("AUTO GENERATED BY GITEA\n")...))
	changed, err = ProjectRepositoryFiles(ctx, bytes.NewReader(generatedAcrossChunks))
	if err != nil || changed.SHA256 != got.SHA256 {
		t.Fatalf("generated-hook marker split across reads was not excluded: summary=%+v err=%v", changed, err)
	}
}

func TestProjectRepositoryFilesAcceptsOnlyRootDirectoryDotSlash(t *testing.T) {
	ctx := context.Background()
	baseline := syntheticGitTar(t)
	want, err := ProjectRepositoryFiles(ctx, bytes.NewReader(baseline))
	if err != nil {
		t.Fatalf("baseline ProjectRepositoryFiles: %v", err)
	}
	for _, rootName := range []string{".", "./"} {
		t.Run(rootName, func(t *testing.T) {
			entries := syntheticGitEntries()
			filtered := entries[:0]
			for _, entry := range entries {
				if entry.header.Name != ".rehearse-runtime/app.ini" && entry.header.Name != "gitea/log/forgejo.log" {
					filtered = append(filtered, entry)
				}
			}
			filtered = append(filtered, tarEntry{header: tar.Header{Name: rootName, Typeflag: tar.TypeDir}})
			archive := makeTar(t, filtered...)
			if _, err := ValidateDataTar(ctx, bytes.NewReader(archive)); err != nil {
				t.Fatalf("archive validator rejected root directory %q: %v", rootName, err)
			}
			got, err := ProjectRepositoryFiles(ctx, bytes.NewReader(archive))
			if err != nil {
				t.Fatalf("repository projection rejected root directory %q: %v", rootName, err)
			}
			if got != want {
				t.Fatalf("root directory metadata changed projection: got=%+v want=%+v", got, want)
			}
		})
	}

	for name, path := range map[string]string{
		"empty path":     "",
		"dot slash file": "./",
		"dot root file":  ".",
	} {
		t.Run(name, func(t *testing.T) {
			if _, _, err := normalizeProjectionTarPath(path, false); err == nil {
				t.Fatalf("unsafe file path %q accepted", path)
			}
		})
	}
}

func TestProjectRepositoryFilesRejectsRepeatedDotSlashPrefix(t *testing.T) {
	ctx := context.Background()
	entries := syntheticGitEntries()
	filtered := entries[:0]
	for _, entry := range entries {
		if entry.header.Name == ".rehearse-runtime/app.ini" || entry.header.Name == "gitea/log/forgejo.log" {
			continue
		}
		entry.header.Name = "././" + entry.header.Name
		filtered = append(filtered, entry)
	}
	archive := makeTar(t, filtered...)
	if _, err := ValidateDataTar(ctx, bytes.NewReader(archive)); err == nil {
		t.Fatal("archive validator accepted repeated relative prefixes")
	}
	if _, err := ProjectRepositoryFiles(ctx, bytes.NewReader(archive)); err == nil {
		t.Fatal("repository projection accepted paths rejected by archive validator")
	}
}

func TestProjectRepositoryFilesRejectsMalformedAndUnsafeTar(t *testing.T) {
	base := "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/"
	for name, entry := range map[string]tarEntry{
		"traversal": {header: tar.Header{Name: base + "refs/../../outside"}},
		"symlink":   {header: tar.Header{Name: base + "refs/link", Typeflag: tar.TypeSymlink, Linkname: "../outside"}},
		"fifo":      {header: tar.Header{Name: base + "run/queue", Typeflag: tar.TypeFifo}},
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := ProjectRepositoryFiles(context.Background(), bytes.NewReader(syntheticGitTar(t, entry))); err == nil {
				t.Fatal("unsafe TAR accepted")
			}
		})
	}
	if _, err := ProjectRepositoryFiles(context.Background(), bytes.NewReader([]byte("not a TAR"))); err == nil {
		t.Fatal("malformed TAR accepted")
	}
	trailing := append(bytes.Clone(syntheticGitTar(t)), []byte("hidden second archive")...)
	if _, err := ProjectRepositoryFiles(context.Background(), bytes.NewReader(trailing)); err == nil {
		t.Fatal("nonzero data after TAR end markers accepted")
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := ProjectRepositoryFiles(ctx, bytes.NewReader(syntheticGitTar(t))); err == nil {
		t.Fatal("canceled TAR projection succeeded")
	}
}

func TestProjectRepositoryFilesRejectsOversizeAndDuplicatePaths(t *testing.T) {
	data := makeTar(t,
		tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/user/repo.git", Typeflag: tar.TypeDir}},
		tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/user/repo.git/HEAD"}, body: []byte("ref: refs/heads/main\n")},
	)
	if _, err := projectRepositoryFiles(context.Background(), bytes.NewReader(data), 1, MaxDataExpandedBytes, MaxDataPathBytesTotal, MaxDataAncestorRefs); err == nil {
		t.Fatal("injected small TAR entry limit was not enforced")
	}
	if _, err := projectRepositoryFiles(context.Background(), bytes.NewReader(data), MaxDataEntries, 1, MaxDataPathBytesTotal, MaxDataAncestorRefs); err == nil {
		t.Fatal("injected small expanded-size limit was not enforced")
	}
	duplicate := syntheticGitTar(t,
		tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/synthetic-user/upgrade-fixture.git/HEAD"}, body: []byte("ref: refs/heads/other\n")},
	)
	if _, err := ProjectRepositoryFiles(context.Background(), bytes.NewReader(duplicate)); err == nil {
		t.Fatal("duplicate normalized path accepted")
	}
	tooLarge := makeTar(t,
		tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/user/repo.git", Typeflag: tar.TypeDir}},
		tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/user/repo.git/HEAD"}},
	)
	setTARHeaderSize(t, tooLarge, 512, uint64(MaxDataFileBytes)+1)
	if _, err := ProjectRepositoryFiles(context.Background(), bytes.NewReader(tooLarge)); err == nil {
		t.Fatal("oversized file accepted")
	}
}

func TestProjectRepositoryFilesEnforcesPathMetadataBudgets(t *testing.T) {
	ctx := context.Background()
	data := syntheticGitTar(t)
	if _, err := projectRepositoryFiles(ctx, bytes.NewReader(data), MaxDataEntries, MaxDataExpandedBytes, 1, MaxDataAncestorRefs); err == nil {
		t.Fatal("aggregate path-byte budget was not enforced")
	}
	if _, err := projectRepositoryFiles(ctx, bytes.NewReader(data), MaxDataEntries, MaxDataExpandedBytes, MaxDataPathBytesTotal, 0); err == nil {
		t.Fatal("aggregate ancestor-reference budget was not enforced")
	}

	deepPath := strings.Repeat("x/", MaxDataPathDepth) + "repo.git/HEAD"
	deep := makeTar(t, tarEntry{header: tar.Header{Name: deepPath}, body: []byte("ref: refs/heads/main\n")})
	if _, err := ProjectRepositoryFiles(ctx, bytes.NewReader(deep)); err == nil {
		t.Fatal("maximum path depth was not enforced")
	}
}

func TestProjectRepositoryFilesRequiresBareRepositoryHead(t *testing.T) {
	noHead := makeTar(t,
		tarEntry{header: tar.Header{Name: "gitea/data/gitea-repositories/user/repo.git/config"}, body: []byte("[core]\nbare = true\n")},
	)
	if _, err := ProjectRepositoryFiles(context.Background(), bytes.NewReader(noHead)); err == nil {
		t.Fatal("repository-shaped data without HEAD was accepted")
	}
}
